with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/rocket-crm/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/rocket-crm/inventory/internal/repository:
    config:
      include-regex: ".*Repository"
      
  github.com/rocket-crm/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/rocket-crm/payment/internal/repository:
    config:
      include-regex: ".*Repository"