services:

  mongo-inventory:
    image: ${MONGO_IMAGE_NAME}

    container_name: mongo-inventory

    env_file:
      - .env

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "${EXTERNAL_MONGO_PORT}:27017"


    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u inventory-service-user -p inventory-service-password --authenticationDatabase admin",
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true

