services:

  mongo-inventory:
    image: mongo:7.0.5

    container_name: mongo-inventory

    environment:
      MONGO_INITDB_DATABASE: inventory-service
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "27017:27017"


    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u inventory-service-user -p inventory-service-password --authenticationDatabase admin",
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true

